### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zlylong** [DoctorFTB/firezone-1.x-self-hosted#1]
WARN[0000] Found orphan containers ([postgres]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
ERROR! Config provider Config.Reader failed with:
** (UndefinedFunctionError) function Domain.Config.Definitions.external_url/0 is undefined or private
    (domain 0.1.0+deadbeef) Domain.Config.Definitions.external_url()
    (domain 0.1.0+deadbeef) lib/domain/config/definition.ex:105: Domain.Config.Definition.fetch_spec_and_opts!/2
    (domain 0.1.0+deadbeef) lib/domain/config/fetcher.ex:14: Domain.Config.Fetcher.fetch_source_and_config/4
    (domain 0.1.0+deadbeef) lib/domain/config.ex:36: Domain.Config.compile_config!/3
    (domain 0.1.0+deadbeef) lib/domain/config/definitions.ex:558: anonymous fn/0 in Domain.Config.Definitions.outbound_email_from/0
    (domain 0.1.0+deadbeef) lib/domain/config/resolver.ex:138: Domain.Config.Resolver.resolve_default_value/1
    (domain 0.1.0+deadbeef) lib/domain/config/fetcher.ex:29: Domain.Config.Fetcher.resolve_value/5
    /app/releases/0.1.0+deadbeef/runtime.exs:228: (file)

Runtime terminating during boot ({undef,[{'Elixir.Domain.Config.Definitions',external_url,[],[]},{'Elixir.Domain.Config.Definition','fetch_spec_and_opts!',2,[{file,"lib/domain/config/definition.ex"},{line,105}]},{'Elixir.Domain.Config.Fetcher',fetch_source_and_config,4,[{file,"lib/domain/config/fetcher.ex"},{line,14}]},{'Elixir.Domain.Config','compile_config!',3,[{file,"lib/domain/config.ex"},{line,36}]},{'Elixir.Domain.Config.Definitions','-outbound_email_from/0-fun-1-',0,[{file,"lib/domain/config/definitions.ex"},{line,558}]},{'Elixir.Domain.Config.Resolver',resolve_default_value,1,[{file,"lib/domain/config/resolver.ex"},{line,138}]},{'Elixir.Domain.Config.Fetcher',resolve_value,5,[{file,"lib/domain/config/fetcher.ex"},{line,29}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.1.0+deadbeef/runtime.exs"},{line,228}]}]})

**Comment by DoctorFTB** [comment]
I think this was due to the FireZone update. I'll check later

**Comment by DoctorFTB** [comment]
Updated!

Can you check? I only tested the portal setup.

**Comment by zlylong** [comment]
> Updated! 更新了！
> 
> Can you check? I only tested the portal setup.你能检查一下吗？我只测试了门户设置。

i change “DOCKER_TAG=latest” to “DOCKER_TAG=1”
this ok
