### ISSUE TITLE
Should have at least two relays

### ISSUE THREAD

**Issue by thomaseizinger** [DoctorFTB/firezone-1.x-self-hosted#2]
Heads-up that a self-hosted user ran into an issue because they only have a single relay. Details are in https://github.com/firezone/firezone/issues/6648.

tl;dr You might want to document as a known issue that gateway also needs to be restarted whenever relay goes down or change the config to recommend at least two relays! :)

**Comment by DoctorFTB** [comment]
Thanks for issue!! I'll update info and setup on the weekends cuz my main job.

**Comment by DoctorFTB** [comment]
As a temporary solution - added `KNOWN ISSUES` section, a little later I will realize two relay setup with different port range

**Comment by thomaseizinger** [comment]
FYI: The port range is configurable so you should be able to split it whilst sharing a single IP.

**Comment by DoctorFTB** [comment]
I'll watch this, thanks!

**Comment by DoctorFTB** [comment]
I created #3 
If you have time, would you watch it?
