### ISSUE TITLE
To relays conflict

### ISSUE THREAD

**Issue by muroed** [DoctorFTB/firezone-1.x-self-hosted#5]
Hi. I have a problem with running 2 relay. In each error, there is such a:

```
Nov 22 06:54:01 firezone-relay-2 sudo[29850]: 2024-11-22T06:54:01.815920Z  INFO phoenix_channel: Connected to portal host=api.vpn.{host}.ru
Nov 22 06:54:02 firezone-relay-2 sudo[29850]: Error: event loop failed
Nov 22 06:54:02 firezone-relay-2 sudo[29850]: Caused by:
Nov 22 06:54:02 firezone-relay-2 sudo[29850]:     Address in use (os error 98)
```

**Comment by muroed** [comment]
<img width="1146" alt="Screenshot 2024-11-22 at 10 01 28" src="https://github.com/user-attachments/assets/08303977-01cb-4c0a-bf1f-d199256a3c3b">

when I enable debug logs, you can see that the first connection is successful, and the re-connection causes an error. At this moment, the portal also shows blinking

https://github.com/user-attachments/assets/09c2c6bb-0227-4562-af8d-7a13239ab408

**Comment by DoctorFTB** [comment]
I think you need to write to support FireZone. I only provided installation and installation support. Also you can check #2
